name: Firebase Functions CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Firebase Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Set up Google Cloud Credentials
        run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/credentials.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}

      - name: Set GOOGLE_APPLICATION_CREDENTIALS
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json

      - name: Deploy to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/credentials.json
        run: firebase deploy --only functions
